# Generated by Django 5.1.7 on 2025-04-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='Sou fã do Mengão',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='Tenho pôster de OP no quarto',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_from_sousa',
            field=models.BooleanField(default=False, verbose_name='Sou de Sousa'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='supports_flamengo',
            field=models.BooleanField(default=False, verbose_name='Sou fã do Mengão'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='watches_one_piece',
            field=models.BooleanField(default=False, verbose_name='Tenho pôster de OP no quarto'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
