# Generated by Django 5.1.7 on 2025-04-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
        ('store', '0003_product_made_in_mari_product_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Cartão de Crédito'), ('debit', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('berries', 'Berries')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('hire_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'order'], name='payment_ord_product_0398db_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greater_than_zero'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.seller'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_ordered'], name='payment_ord_date_or_dcc9db_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller'], name='payment_ord_seller__ac265f_idx'),
        ),
    ]
